# Generated by Django 4.2 on 2026-02-05 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parceldetail',
            table=None,
        ),
    ]
